name: get_arch_quick_start
description: GetArch quick start support
version: 2.2.0
repository: https://github.com/Hu-Wentao/get_arch_quick_start

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  get_arch_core:
    git:
      url: https://e.coding.net/donove/flutter/get_arch_core
      ref: v2.3
  injectable: 
#  yaml: ^3.1.0
  # dio: ^4.0.0
  # pretty_dio_logger: null
  # web_socket_channel: ^2.0.0
  # hive: ^2.0.2
  # path_provider: ^2.0.0
  nil: null
dev_dependencies:
  flutter_test:
    sdk: flutter
# dev_dependencies中的内容只能作用于当前项目,请根据自己的项目添加对应依赖
#
  injectable_generator: null  
  build_runner: null
#  mockito: ^4.1.1

# dependency_overrides:
  # get_arch_core:
  #   path: D:\flutter_arch\get_arch_core

flutter:
